### ISSUE TITLE
Wrong number of parameters

### ISSUE THREAD

**Issue by Drarig29** [ivaaaan/jiraf#5]
I'm trying to use the command as simple as this: `jiraf PROJECT-123` and it doesn't work.

I have this error: https://github.com/ivaaaan/jiraf/blob/496632856d58d78f40dad274f0227695aa9aabb8/main.go#L56-L57

Usually, the executable filename is included in the list of arguments in other languages, maybe it's the same with go. And maybe you have never tested your CLI while being installed? Idk

**Comment by ivaaaan** [comment]
Fixed as well. Thanks for your feedback
